version: '3.3'

services:

  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  server:
    container_name: server
    build: ./docker/server
    image: msterhuj/serverside
    environment:
      - "IP_RANGE_LIST=192.168.0.0/24"
      - "MONGO_HOST=mongo"
      - "MONGO_POST=27017"

  client:
    build: ./docker/client
    image: msterhuj/clientside
    depends_on:
      - server