version: '3.3'

services:

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./mongodb_data/:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_ui
    ports:
      - 8081:8081
    depends_on:
      - mongo

  server:
    container_name: server
    build: server
    image: msterhuj/serverside
    environment:
      - "IP_RANGE_LIST=192.168.0.0/24"
    depends_on:
      - mongo

  client:
    build: client
    image: msterhuj/clientside
    environment:
      - "MONGO_HOST=mongodb://mongo:27017/"
      - "MONGO_DB_NAME=ipisinthisdb"
    depends_on:
      - mongo
      - server